# Postgres and pgAdmin4 stack for development

version: "3.1"

services:
  server:
    image: node-memories
    depends_on:
      - db
    restart: always
    ports:
      - "3333:3333"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "memories"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "malheiroanderson97@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - db
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
